# Generated by Django 5.2.7 on 2025-10-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_items_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Best_Sellers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='Featured_Products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='New_Arrivals',
            field=models.BooleanField(default=False),
        ),
    ]
