# Generated by Django 5.2.5 on 2025-10-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_items_best_sellers_items_featured_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='tag',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
    ]
