# Generated by Django 5.2.7 on 2025-10-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0010_category_static_image_items_static_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="image",
        ),
    ]
