# Generated by Django 5.2.7 on 2025-10-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0011_remove_items_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="default_weight",
            field=models.CharField(
                default="500g", help_text="Default weight option", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="weight_prices",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"250g": {"price": 100, "old_price": 120}, "500g": {"price": 200, "old_price": 240}}',
            ),
        ),
    ]
