# Generated by Django 5.2.7 on 2025-10-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogs",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Blogs"},
        ),
        migrations.AddField(
            model_name="blogs",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="Short description for blog card", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="blogs",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
