# Generated by Django 5.2.7 on 2025-10-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0003_blogs_static_image_alter_blogs_featured_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="featured_image",
        ),
    ]
