# Generated by Django 5.2.7 on 2025-10-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0005_remove_blogs_static_image_blogs_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
