# Generated by Django 5.2.7 on 2025-10-30 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Home", "0011_remove_items_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        help_text="e.g., 500g, 1kg, 2kg, 5kg", max_length=50
                    ),
                ),
                (
                    "weight_in_grams",
                    models.IntegerField(help_text="Weight in grams for sorting"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default weight option for this product",
                    ),
                ),
                ("in_stock", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_variants",
                        to="Home.items",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Weight Variant",
                "verbose_name_plural": "Product Weight Variants",
                "ordering": ["weight_in_grams"],
                "unique_together": {("product", "weight")},
            },
        ),
    ]
