# Generated by Django 5.2.7 on 2025-10-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_tag_remove_featured_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='tag',
        ),
        migrations.AddField(
            model_name='items',
            name='tag',
            field=models.ManyToManyField(to='Home.tag'),
        ),
    ]
