# Generated by Django 5.2.7 on 2025-10-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0002_alter_blogs_options_blogs_excerpt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="static_image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="featured_image",
            field=models.ImageField(null=True, upload_to="blog_images/"),
        ),
    ]
