# Generated by Django 5.2.7 on 2025-10-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0004_remove_blogs_featured_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="static_image",
        ),
        migrations.AddField(
            model_name="blogs",
            name="image",
            field=models.ImageField(null=True, upload_to="..static/images/"),
        ),
    ]
